### PR TITLE
[Weight] Add ctors

### LINKED ISSUE #652: copy assigment of Weight must be disabled
Copy assignment of weight must be disabled.
It is only used in `Layer::copy` with wrong usage where weights aren't actually copied.
Refer to discussion https://github.com/nnstreamer/nntrainer/pull/648#discussion_r508174968

### PR DESCRIPTION
**Pull request by zhoonit**
Weight did not have copy/move ctor which they should have.
This patch adds them.

Resolves #652 

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com>

### CODE REVIEW

File: nntrainer/include/weight.h [hunk 1]
```diff
@@ -168,6 +181,7 @@ class Weight {
    */
   Tensor &getGradientRef() { return grad; }
 
+private:
```
Comment (kparichay) [inline nntrainer/include/weight.h:184]: unnecessary change

File: nntrainer/include/weight.h [hunk 2]
```diff
@@ -101,6 +101,20 @@ class Weight {
     swap(lhs.name, rhs.name);
   }
 
+  /**
+   * @brief Copy constructor for weight
+   *
+   * @param rhs weight to construct from
+   */
+  Weight(const Weight &rhs) = default;
```
Comment (kparichay) [inline nntrainer/include/weight.h:109]: is this essentially needed? If some layer writer uses these, then the weights of both the layers would be bonded together
and create nasty bugs.

Comment (zhoonit) [reply nntrainer/include/weight.h:109]: If we have a copy assignment, we need a copy constructor.  If we are gonna delete a copy assignment, I think it's fine for me.  I am gonna be using this for the integrated tests, btw, but I can work around I think we decide to not allow copy ctor/assignment.

I got what you mean though, it seems that there should be a broader patch that changes copy assignment as well.

File: nntrainer/include/weight.h (hunk 1 above)
Comment (zhoonit) [reply nntrainer/include/weight.h:184]: This should have gone to a separate patch. I'll move this after the discussion. 

I am thinking to open this up for the test. Is there a reason Ref 's are private?

Comment (kparichay) [reply nntrainer/include/weight.h:184]: Yes, so that any other class other the friend class cannot directly update this as an operation. 
I know `float * data` is accessible, but if someone is changing that, its intentional.
Getting weight by reference is only allowed for object owners which is this case is the layer and its optimizer.

File: nntrainer/include/weight.h (hunk 2 above)
Comment (kparichay) [reply nntrainer/include/weight.h:109]: Copy assignment is wrong. 
It is currently only used in `Layer::copy` with wrong usage. It must create a deep copy of the weights but it rather binds the weights of the layer together as copy constructor of Tensor binds the memory together.

File: nntrainer/include/weight.h (hunk 1 above)
Comment (zhoonit) [reply nntrainer/include/weight.h]: The change has been reverted. I'll use data for now.

**Review by kparichay — COMMENTED** [review]
LGTM
good bug fix

**Review by kparichay — APPROVED** [review]

**Review by jijoongmoon — APPROVED** [review]
LGTM
