### PR TITLE
[Fix] Assign default value for max_deriv size @open sesame 12/29 15:57

### LINKED ISSUE #834: Current upstream/main is not passing unittest
commit version 81dd228f 

From `ninja test` with vanilla `meson build`

```
 1/22 app_knn                        OK             5.37s
 2/22 app_logistic                   OK             2.79s
 3/22 app_DeepQ                      FAIL           0.35s (killed by signal 6 SIGABRT)
 4/22 app_classification             OK             0.44s
 5/22 app_classification_func        OK             0.30s
 6/22 app_training                   FAIL           4.77s (killed by signal 9 SIGKILL)
 7/22 unittest_tizen_capi            FAIL           11.43s (killed by signal 9 SIGKILL)
 8/22 unittest_tizen_capi_layer      OK             0.28s
 9/22 unittest_tizen_capi_optimizer  OK             0.32s
10/22 unittest_tizen_capi_dataset    OK             0.44s
11/22 unittest_nntrainer_activations OK             0.31s
12/22 unittest_nntrainer_internal    OK             0.48s
13/22 unittest_nntrainer_layers      FAIL           3.64s (killed by signal 9 SIGKILL)
14/22 unittest_nntrainer_lazy_tensor OK             0.09s
15/22 unittest_nntrainer_tensor      OK             0.13s
16/22 unittest_util_func             OK             0.10s
17/22 unittest_databuffer_file       OK             0.34s
18/22 unittest_nntrainer_modelfile   OK             1.06s
19/22 unittest_nntrainer_models      FAIL           2.17s (killed by signal 9 SIGKILL)
20/22 unittest_nntrainer_graph       OK             2.81s
21/22 unittest_nntrainer_appcontext  OK             0.09s
22/22 unittest_ccapi                 FAIL           2.55s (killed by signal 9 SIGKILL)
```

### PR DESCRIPTION
**Pull request by zhoonit**
This patch initialize max_dervative_size to avoid unexpected termination

resolves #834

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com>

### CODE REVIEW

**Review by jijoongmoon — APPROVED** [review]
LGTM

File: nntrainer/tensor/manager.cpp [hunk 1]
```diff
@@ -120,13 +120,16 @@ MMapedMemory::~MMapedMemory() {
   ml_logd("[MMapedMemory] buf released");
 }
 
-Manager::Manager(bool enable_gradient_memory_opt_, bool use_shared_memory_) :
+Manager::Manager(bool enable_gradient_memory_opt_,
+                 bool enable_derivative_memory_opt_,
```
Comment (kparichay) [inline nntrainer/tensor/manager.cpp:124]: Please check https://github.com/nnstreamer/nntrainer/pull/830#discussion_r549601909

**Review by kparichay — APPROVED** [review]
Other than the minor comment, LGTM

File: nntrainer/tensor/manager.cpp (hunk 1 above)
Comment (zhoonit) [reply nntrainer/tensor/manager.cpp:124]: Yes this is affecting the unittest, I'll make another commit to resolve the issue :)
