### PR TITLE
[Optim] Add shortcut to dot product @open sesame 12/14 22:55

### LINKED ISSUE #799: Tensor dot operation optimization
SGEMM is not optimized for vector * matrix operation,  should handle vector * matrix operation in Tensor Dot operation

### LINKED ISSUE #801: Tensor dot ld* is incorrect
lda, ldb should be actual memory layout before applying transpose but it was set after transpose.

### PR DESCRIPTION
**Pull request by zhoonit**
- ~**#797** [Profiler] Separate Profiler for wider use~
- ~**#797** [Test] Add profiler test~
- ~**#797** [Profiler] Add basic profilerlistener~
- [Fix] fix lda, ldb param
```
**Changes proposed in this PR:**
- lda, ldb, ldc is for layout so it should be set in terms of memory
layout, this patch fixes the issue while adding a corresponding test

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com>
```
resolves #801

- [Optim] Add shortcut to dot product
```
When dimension is 1, it is vector by matrix or vector by vector
multiplication. This patch adds a shortcut in that situation

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com>
```
resolves #799

### CODE REVIEW

**Review by jijoongmoon — APPROVED** [review]
LGTM

File: nntrainer/tensor/tensor.cpp [hunk 1]
```diff
@@ -633,9 +633,33 @@ Tensor &Tensor::dot(Tensor const &m, Tensor &result, bool trans,
   float *rdata = result.getData();
   const float alpha = 1.0f;
   const float beta = 0.0f;
-
   enum CBLAS_TRANSPOSE transA = trans ? CblasTrans : CblasNoTrans;
   enum CBLAS_TRANSPOSE transB = trans_m ? CblasTrans : CblasNoTrans;
+
+  /// shortcut calculation in case of vector
+  /// case1: (1 * K) X (K * 1)
+  if (M == 1 && N == 1) {
```
Comment (kparichay) [inline nntrainer/tensor/tensor.cpp:641]: in this scenario, trans are directly ignored? If yes, then please add that to the documentation of the function.

File: nntrainer/tensor/tensor.cpp [hunk 2]
```diff
@@ -633,9 +633,33 @@ Tensor &Tensor::dot(Tensor const &m, Tensor &result, bool trans,
...
+    *rdata = sdot(K, data, 1, mdata, 1);
+    return result;
+  }
+
+  /// case2: (M * K) X (K * 1)
+  if (N == 1) {
+    sgemv(CblasRowMajor, transA, dim1, dim2, alpha, data, lda, mdata, 1, beta,
```
Comment (kparichay) [inline nntrainer/tensor/tensor.cpp:648]: similarly add that transB is ignored. If not ignored, it would generate `(M * K) X (1 * K)` which should ideally give an error. As this is just optimization and not changing functional behavior, lets add it as a documentation.

Comment (kparichay) [reply nntrainer/tensor/tensor.cpp:648]: or add a check that transB must be false (which would be the case if gemm was being used here.)

File: nntrainer/tensor/tensor.cpp [hunk 3]
```diff
@@ -633,9 +633,33 @@ Tensor &Tensor::dot(Tensor const &m, Tensor &result, bool trans,
...
+
+  /// shortcut calculation in case of vector
+  /// case1: (1 * K) X (K * 1)
+  if (M == 1 && N == 1) {
+    *rdata = sdot(K, data, 1, mdata, 1);
+    return result;
+  }
+
+  /// case2: (M * K) X (K * 1)
+  if (N == 1) {
```
Comment (kparichay) [inline nntrainer/tensor/tensor.cpp:647]: how about making these all else if and lastly else with just 1 return statement?

File: nntrainer/tensor/tensor.cpp [hunk 4]
```diff
@@ -633,9 +633,33 @@ Tensor &Tensor::dot(Tensor const &m, Tensor &result, bool trans,
...
+    sgemv(CblasRowMajor, transA, dim1, dim2, alpha, data, lda, mdata, 1, beta,
+          rdata, 1);
+    return result;
+  }
+
+  /// case3: (1 * K) X (K * N) = 1 * N = R
+  /// = R^T = (K * N) ^T * (1 * K)
```
Comment (kparichay) [inline nntrainer/tensor/tensor.cpp:654]: this will become `(K * N) ^T * (1 * K) ^ T` -> `N * K X K * 1` right? S
Just like above, please add check for transA or add comment that its not needed.

**Comment by kparichay** [comment]
I have left some minor comments so that the behavior of dot remains same.
Overall good job in finding the underlying issue and solving it.

File: nntrainer/tensor/tensor.cpp (hunk 1 above)
Comment (zhoonit) [reply nntrainer/tensor/tensor.cpp:641]: for a vector A (1 * K), A^T == A in terms of memory layout. The case is considered in the test :)

File: nntrainer/tensor/tensor.cpp (hunk 2 above)
Comment (zhoonit) [reply nntrainer/tensor/tensor.cpp:648]: `(1 * K) == (K * 1)` in terms of memory layout. This is considered and tested in the unittest. Thanks :)

File: nntrainer/tensor/tensor.cpp (hunk 4 above)
Comment (zhoonit) [reply nntrainer/tensor/tensor.cpp:654]: I'll add additional comment that (1 * K) == (K * 1) 👍

File: nntrainer/tensor/tensor.cpp (hunk 3 above)
Comment (zhoonit) [reply nntrainer/tensor/tensor.cpp:647]: Done

File: nntrainer/tensor/tensor.cpp (hunk 2 above)
Comment (zhoonit) [reply nntrainer/tensor/tensor.cpp:647]: Oh, If you mean `(M * K) X (1 * K)` giving an error, it is handled before getting in to this line.

File: nntrainer/tensor/tensor.cpp (hunk 1 above)
Comment (kparichay) [reply nntrainer/tensor/tensor.cpp:642]: Right, `1*k` and `k*1` are same from the perspective from the memory, but in tensor_dim, they are not. Hence, it must be cleared.

Comment (zhoonit) [reply nntrainer/tensor/tensor.cpp:646]: Ahh, sorry for the misunderstanding, trans are not ignored as trans are resolved to get appropriate (N, M, K) before entering this line. 
Please note that N, M, K denotes a placeholder for (N * K) x (K * M). So case of (1 * K) X (1 * K) is not possible as it should be (1 * K) X (1 * M).

I added some more notes here to clarify.

Comment (kparichay) [reply nntrainer/tensor/tensor.cpp:646]: thanks

**Review by kparichay — APPROVED** [review]
LGTM
