### PR TITLE
Additional validation and fixes for network::init

### LINKED ISSUE #390: Activation layer type itself is making activation again
because we always make layer even for the activation layer itself, it is messing up activation ini

### PR DESCRIPTION
**Pull request by zhoonit**
**Changes proposed in this PR:**
- Add term `realization`. This term denotes that enum type is turned
into an instance
- Change `initActivationLayer` -> `realizeActivationType`
- Change `initFlattenLayer` -> `relizeFlattenType`
- Delete `_make_act_layer`
- Add `TensorDim::isEmpty()`
- Clarify `checkValidation` -> `isInitializable` and move beforehand
validation logics
- Fix logic that prevents double activation
- Move layer name validaton phase `addLayer` -> `isInitializable`
- Prevent realization of `ACT_NONE`
- Sort unittest_modelfile order and update comments
- Enable few test cases

Resolves #390
See also #388

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com>

### CODE REVIEW

File: api/capi/src/nntrainer.cpp [hunk 1]
```diff
@@ -216,7 +216,7 @@ int ml_train_model_compile(ml_train_model_h model, ...) {
   if (status != ML_ERROR_NONE)
     return status;
 
-  f = [&]() { return NN->checkValidation(); };
+  f = [&]() { return NN->isInitializable(); };
```
Comment (jijoongmoon) [inline api/capi/src/nntrainer.cpp:219]: I think this is for just checking the configuration before Initialize.

Comment (zhoonit) [reply api/capi/src/nntrainer.cpp:219]: Yes. It checks if it is able to initialize. So I clarified the name
