### PR TITLE
[tensor/manager] Fix in-place layer optimization bug

### LINKED ISSUE #878: InPlace layer optimization bug
In-place layer optimization has yet another bug.

In general, with derivative optimization, the output tensor and derivative tensor of a layer share the same memory.
With in-place layer optimization, in-place layers do not allocate their own output tensors, but rather use their neighbor's tensors. To handle the derivative memory requirement, in-place layers use a shared memory of derivatives among all the in-place layers.

Current in-place layer optimization deletes the tensors from the previous layers and re-assigns tensors from the current layer (which will behave in-place) to the previous layer. However, this creates an issue that the derivative memory management is different for the current layer and the previous layer. 
For example, with FC layer and activation layer, with the activation layer in-place, they will share the same input/output tensors. But the derivative memory management for the two layers has to be handled separetely.

### PR DESCRIPTION
**Pull request by kparichay**
**Commit 1**: [tensor] Support late memory allocation for tensors
Support late memory allocation for tensors.
This helps create tensor wrapper elements and allocate memory
later when needed.
This allows finalizing the graph, creating all the tensors and graph
connections for all the layers which can be stored in offline setup
and then loaded directly from file.

This decoupling allows reusing tensors with every call to train
where we can allocate and deallocate memory without having to create
and do tensor management again and again.

In short term, this is necessary for in-place layer optimization.
See Also #879

The implementation requires caching the source tensor when creating
shared tensors as shared tensors cannot be created unless the source
tensor memory has been allocated.

**Commit 2**: In-place bug fix 
This patch applied bug fix for in-place layer optimization.
As in-place layers and other layers manages derivative memory
differently, in-place layers cannot directly re-use the tensors
of their neighboring layers. But rather have to use tensors differently.
This patch applies this bug-fix.
See also #878

**Commit 3:** [Manager] Support lazy memory allocation with manager
Support lazy memory allocation with manager

**Commit 4:** [bug fixes] Update shared mem and in-place opt
Update shared memory and in-place opt to share memory with previous
layers with different strategies based on the type of optimization the
layer is doing for reducing its memory usage.

Added weight and var_grad to create weight/var_grad with lazy
memory allocation.
Update SrcSharedTensor to remove the check is source is allocated
as it cannot be guaranteed.
Bug fix for tensor is allocated

Update nntrainer extension for nnstreamer to use a different
ini file for inference which does not require changing batch size.
Added minor bug fixes to the patch

**Commit 5:** [tensor] Split tensor constructor into 2    
Create a new tensor constructor for lazy allocation
    than adding the lazy allocation feature to the existing one

Resolves #878
See also #876

**Self evaluation:**
1. Build test: [x]Passed [ ]Failed [ ]Skipped
2. Run test: [x]Passed [ ]Failed [ ]Skipped

Signed-off-by: Parichay Kapoor <pk.kapoor@samsung.com>

### CODE REVIEW

File: nntrainer/tensor/tensor.cpp [hunk 1]
```diff
@@ -80,18 +80,80 @@ static auto rng = [] {
...
+ */
+class SrcSharedTensor {
+public:
+  /**
+   * @brief   Constructor for the class
+   */
+  SrcSharedTensor(): src(nullptr), off(0) {}
+
+  SrcSharedTensor(const Tensor *tensor, unsigned int offset): src(tensor), off(offset) {}
+
```
Comment (jijoongmoon) [inline nntrainer/tensor/tensor.cpp:116]: If we get the tensor obj from SrcSharedTenor with offset.. I think we need to compare the last buffer from offset to prevent the overflow.

File: nntrainer/tensor/tensor.cpp [hunk 2]
```diff
@@ -80,18 +80,80 @@ static auto rng = [] {
...
+};
+
+void Tensor::allocate() {
+  if (data)
+    /// already allocated
+    return;
+
+  if (src_tensor) {
+    /// allocate data based on the source tensor
+    data = std::shared_ptr<float>(src_tensor->tensor()->data, src_tensor->tensor()->data.get() + src_tensor->offset());
```
Comment (jijoongmoon) [inline nntrainer/tensor/tensor.cpp]: If we get the tensor obj from SrcSharedTenor with offset.. I think we need to compare the last buffer from offset to prevent the overflow.

File: nntrainer/tensor/tensor.cpp [hunk 3]
```diff
@@ -336,9 +398,17 @@ Tensor Tensor::getSharedDataTensor(const TensorDim dim_,
...
-  ret.data = std::shared_ptr<float>(this->data, this->data.get() + offset);
   ret.strides = ret.dim.computeStrides();
 
+  /**
+   * In this case, its the caller's responsibility to ensure that allocate() is
+   * called for this function before operating on this tensor.
+   */
+  if (this->data)
+    ret.data = std::shared_ptr<float>(this->data, this->data.get() + offset);
+  else
```
Comment (jijoongmoon) [inline nntrainer/tensor/tensor.cpp]: Is it possible to get the data from this->data.get()+offset1 to offset2?

File: nntrainer/tensor/tensor.cpp [hunk 4]
```diff
@@ -80,18 +80,80 @@ static auto rng = [] {
...
       copy(buf);
   }
 }
 
+/**
+ * @class SrcSharedTensor
+ * @brief Source of the shared tensor
+ */
+class SrcSharedTensor {
+public:
```
Comment (jijoongmoon) [inline nntrainer/tensor/tensor.cpp:107]: I wonder.. does the tensor has this SrcSharedTensor always? How about just set the data with data pointer from shared tensor ?

File: nntrainer/tensor/tensor.cpp (hunk 2 above)
Comment (kparichay) [reply nntrainer/tensor/tensor.cpp]: This is updated in the last commit of this PR, where the src_tensor is always the original tensor which will allocate the memory, and offset is set based on the original source tensor.

File: nntrainer/tensor/tensor.cpp (hunk 3 above)
Comment (kparichay) [reply nntrainer/tensor/tensor.cpp]: I don't understand the reference to offset1 and offset2 here. Can you please elaborate?

File: nntrainer/tensor/tensor.cpp (hunk 4 above)
Comment (kparichay) [reply nntrainer/tensor/tensor.cpp:107]: > How about just set the data with data pointer from shared tensor ?

That is one approach. However, with this, there need to be two extra variables - offset from srcSharedTensor, and a variable to indicate if this actual data or srcSharedTensor, and creates Tensor object more complicated and heavy.
With SrcSharedTensor, the Tensor class size remains cleaner with smaller increase in object size.

File: nntrainer/tensor/tensor.cpp (hunk 3 above)
Comment (jijoongmoon) [reply nntrainer/tensor/tensor.cpp]: What I means.. making shared tensor from in the middle of memory chunck.

File: nntrainer/graph/network_graph.cpp [hunk 5]
```diff
@@ -576,8 +576,22 @@ void NetworkGraph::inPlaceOptimize(const std::string &layer_type,
...
+      if (l->getType() == BatchNormalizationLayer::type) {
+        prev_layer->net_hidden[loc] = l->net_hidden[0]; // O1 = O2
+      } else if (l->getType() == ActivationLayer::type) {
+        // THIS IS NOT WORKING BECAUSE INITIALIZES MAKES NEW SHARED_PTR OF TENSOR
+        // THAN KEEPING THE SAME SHARED_PTR AND JUST CHANGING THE TENSOR IN IT
+        prev_layer->net_hidden[loc]->getGradientRef() =
+          l->net_hidden[0]->getVariableRef(); // O1.G = O2.V
+        prev_layer->net_hidden[loc]->getVariableRef() =
+          l->net_hidden[0]->getVariableRef(); // O1.V = O2.V
+      }
```
Comment (jijoongmoon) [inline nntrainer/graph/network_graph.cpp:608]: is it right to point grad and var to 02.v?

File: nntrainer/layers/conv2d_layer.cpp [hunk 6]
```diff
@@ -77,8 +77,8 @@ int Conv2DLayer::initialize(Manager &manager) {
 
   if (weights.empty()) {
     weights.reserve(2);
-    weights.emplace_back(dim, weight_initializer, true, kernelPrefix);
-    weights.emplace_back(bias_dim, bias_initializer, true, biasPrefix);
+    weights.emplace_back(dim, weight_initializer, true, false, kernelPrefix);
+    weights.emplace_back(bias_dim, bias_initializer, true, false, biasPrefix);
```
Comment (jijoongmoon) [inline nntrainer/layers/conv2d_layer.cpp]: So.. when we initialize layer, there is no memory allocation?

File: nntrainer/tensor/tensor.cpp [hunk 7]
```diff
@@ -327,6 +387,17 @@ Tensor Tensor::getBatchSlice(unsigned int offset, unsigned int size) const {
...
 
+void Tensor::createSharedDataTensor(const Tensor &src, Tensor &dest,
+                                    unsigned int offset) {
+  if (src.data)
+    dest.data = std::shared_ptr<float>(src.data, src.data.get() + offset);
+  else if (!src.src_tensor)
+    dest.src_tensor = std::make_shared<SrcSharedTensor>(&src, offset);
+  else
+    dest.src_tensor = std::make_shared<SrcSharedTensor>(
+      src.src_tensor->tensor(), offset + src.src_tensor->offset());
```
Comment (jijoongmoon) [inline nntrainer/tensor/tensor.cpp:398]: So.. if there is src.src_tensor, then we are going to use memory from src.offset() to offset of dest? If it is, then it is not possible to share from src.data?

File: nntrainer/tensor/tensor.cpp [hunk 8]
```diff
@@ -80,18 +80,80 @@ static auto rng = [] {
   return rng;
 }();
 
-Tensor::Tensor(const TensorDim &d, const float *buf) : Tensor() {
+Tensor::Tensor(const TensorDim &d, const float *buf, bool alloc_now) : Tensor() {
```
Comment (zhoonit) [inline nntrainer/tensor/tensor.cpp]: Q. giving `buf` means `alloc_now` always true?

File: nntrainer/tensor/tensor.cpp [hunk 9]
```diff
@@ -80,18 +80,80 @@ static auto rng = [] {
...
+      throw std::runtime_error("Accessing empty src tensor");
+
+    /**
+     * Allocate source tensor if not already allocated.
+     */
+    if (!src->isAllocated())
+      throw std::runtime_error("Source tensor must be allocated before allocating dependent tensors");
+      // src->allocate();
+
+    return src;
```
Comment (zhoonit) [inline nntrainer/tensor/tensor.cpp:124]: return src + offset?

File: nntrainer/tensor/tensor.cpp (hunk 3 above)
Comment (kparichay) [reply nntrainer/tensor/tensor.cpp]: To remedy this, in the last commit, if the source tensor (say `t_s1`) provided depends on another source tensor (say `t_s2`), then the tensor to be made in this situation is made to directly depend on `t_s2`.

File: nntrainer/graph/network_graph.cpp (hunk 5 above)
Comment (kparichay) [reply nntrainer/graph/network_graph.cpp:608]: Yes, this is intended. The derivative optimization of different layers happens differently.
For layers working in-place, like activation, these layers share derivative from common shared memory.
However, for layers that are not in-place, these layers use their output memory as the derivative memory.

File: nntrainer/layers/conv2d_layer.cpp (hunk 6 above)
Comment (kparichay) [reply nntrainer/layers/conv2d_layer.cpp]: Right.

File: nntrainer/tensor/tensor.h [hunk 10]
```diff
@@ -841,8 +863,17 @@ class Tensor {
...
+
   std::shared_ptr<float> data;
 
+  /**<
+   * When using shared_data with tensor, this stores the ptr of the source
+   * tensor which handles the full memory. If tensor data is already allocated,
+   * this does not affect the tensor. If the tensor data is not allocated, and
+   * src_ptr is valid, this tensor will use the memory allocated by the src_ptr
+   */
+  std::shared_ptr<SrcSharedTensor> src_tensor;
```
Comment (zhoonit) [inline nntrainer/tensor/tensor.h:888]: I think, in the long term, we should have storage object or equivalent to manage the memory, tensor often used as a wrapper to a memory. Thus making our intentions more clear by using storage if we are to manage memory.

File: nntrainer/tensor/tensor.cpp (hunk 2 above)
Comment (zhoonit) [inline nntrainer/tensor/tensor.cpp]: how about hiding this logic into `src_tensor->allocate()`

File: nntrainer/graph/network_graph.cpp [hunk 11]
```diff
@@ -576,8 +576,22 @@ void NetworkGraph::inPlaceOptimize(const std::string &layer_type,
         continue;
 
       /** Share tensor with next layer */
-      l->net_input[0] = l->net_hidden[0];
-      prev_layer->net_hidden[loc] = l->net_hidden[0];
+      l->net_input[0] = l->net_hidden[0]; // I2 = O2
```
Comment (zhoonit) [inline nntrainer/graph/network_graph.cpp]: Q. what is I2 O2 O1.G O2.V??

File: nntrainer/tensor/tensor.cpp (hunk 7 above)
Comment (kparichay) [reply nntrainer/tensor/tensor.cpp:398]: The function first check If `src.data` exists (meaning tensor already has memory allocated). If it is, then we directly make this tensor based on the src tensor.
If `src.data` does not exist (meaning tensor does not memory allocated), and `src.src_tensor` does not exist (meaning the src tensor does not exist on other tensor), then create a SrcTensor around the src.
If `src.src_tensor` exists, then use the `src.src_tensor` to create the required `src_tensor` to avoid recursive dependency.
Some more explanation in https://github.com/nnstreamer/nntrainer/pull/880#discussion_r567550639.

> So.. if there is src.src_tensor, then we are going to use memory from src.offset() to offset of dest? If it is, then it is not possible to share from src.data?

The function first tries to share from `src.data`. If src.data is not yet allocated, then it goes to src_tensor.

File: nntrainer/tensor/tensor.h [hunk 12]
```diff
@@ -57,12 +58,17 @@ class Tensor {
...
 
   /**
    * @brief     Constructor of Tensor with dimension/buf
+   * @param d Tensor dim for this tensor
+   * @param bug buffer
+   * @alloc_now If the memory of the tensor must be allocated
+   * @throws if buf is not null and allow_now is false
    */
-  Tensor(const TensorDim &d, const float *buf = nullptr);
+  Tensor(const TensorDim &d, const float *buf = nullptr, bool alloc_now = true);
```
[the remark this answers is not in the document]
Comment (kparichay) [reply nntrainer/tensor/tensor.h:71]: Tensor(TensorDim, buf = nullptr, alloc_now) would also be needed, where we can store `buf` in the `SrcSharedTensor`?

File: nntrainer/graph/network_graph.cpp (hunk 11 above)
Comment (kparichay) [reply nntrainer/graph/network_graph.cpp]: I will add details in comments.

File: nntrainer/graph/network_graph.cpp [hunk 13]
```diff
@@ -576,8 +576,22 @@ void NetworkGraph::inPlaceOptimize(const std::string &layer_type,
...
+      if (l->getType() == BatchNormalizationLayer::type) {
```
Comment (zhoonit) [inline nntrainer/graph/network_graph.cpp:581]: caution for this if,
we will going to need `is_batchnorm_type`, `is_activation_type` kind of property if this cannot be unified.

File: nntrainer/graph/network_graph.cpp (hunk 11 above)
Comment (zhoonit) [reply nntrainer/graph/network_graph.cpp]: Input to current (I2)
Output to current (O2)

File: nntrainer/graph/network_graph.cpp (hunk 13 above)
Comment (zhoonit) [reply nntrainer/graph/network_graph.cpp:581]: We could have strategy instead I guess?

Comment (kparichay) [reply nntrainer/graph/network_graph.cpp:581]: The strategy is to support `supportInPlace()` in the layer.

Comment (kparichay) [reply nntrainer/graph/network_graph.cpp:581]: #867

File: nntrainer/graph/network_graph.cpp [hunk 14]
```diff
@@ -576,8 +576,22 @@ void NetworkGraph::inPlaceOptimize(const std::string &layer_type,
...
+        prev_layer->net_hidden[loc] = l->net_hidden[0]; // O1 = O2
+      } else if (l->getType() == ActivationLayer::type) {
+        // THIS IS NOT WORKING BECAUSE INITIALIZES MAKES NEW SHARED_PTR OF TENSOR
+        // THAN KEEPING THE SAME SHARED_PTR AND JUST CHANGING THE TENSOR IN IT
+        prev_layer->net_hidden[loc]->getGradientRef() =
+          l->net_hidden[0]->getVariableRef(); // O1.G = O2.V
```
Comment (zhoonit) [inline nntrainer/graph/network_graph.cpp]: How about having a designated memory(for safety) or at least alias for readability?

File: nntrainer/graph/network_graph.cpp [hunk 15]
```diff
@@ -576,8 +576,22 @@ void NetworkGraph::inPlaceOptimize(const std::string &layer_type,
...
+        prev_layer->net_hidden[loc]->getVariableRef() =
+          l->net_hidden[0]->getVariableRef(); // O1.V = O2.V
+      }
+
+      /** prev layer should use this shared output for derivative though */
+      // prev_layer->net_hidden[loc] =
```
Comment (zhoonit) [inline nntrainer/graph/network_graph.cpp]: comment intended?

File: nntrainer/tensor/tensor.h (hunk 10 above)
Comment (kparichay) [reply nntrainer/tensor/tensor.h:888]: Yes, the storage object would wrap both `data` and `src_tensor`.
It will be done. For now, this PR has been rushed to solved the bug ASAP.

File: nntrainer/layers/conv2d_layer.cpp (hunk 6 above)
Comment (zhoonit) [reply nntrainer/layers/conv2d_layer.cpp]: Not for the PR, but there is an idea. 

manager calls layer::get_weight() before layer::initialize() and it tracks all the weights. we can extract this to a manager (idea for api change)

File: nntrainer/tensor/manager.cpp [hunk 16]
```diff
@@ -177,23 +177,23 @@ void Manager::trackWeights(std::vector<Weight> &ws) {
 }
 
 Manager::AllocFunc Manager::getAllocFunc(bool is_weight) {
-  AllocFunc allocate_none = [](const TensorDim &dim, size_t) {
+  AllocFunc allocate_none = [](const TensorDim &dim, unsigned int) {
```
Comment (zhoonit) [inline nntrainer/tensor/manager.cpp:180]: any reason for the change?

File: nntrainer/tensor/manager.cpp [hunk 17]
```diff
@@ -206,16 +206,16 @@ Manager::AllocFunc Manager::getAllocFunc(bool is_weight) {
...
-      size_t grad_size =
+      unsigned int grad_size =
         enable_gradient_memory_opt ? max_grad_size : total_grad_size;
       allocate_func = get_allocfunc(grad_size, grad_mmaped_memory);
     }
   } else if (!is_weight) {
     /** only for gradients */
     if (max_grad_size > 0 && enable_gradient_memory_opt) {
-      Tensor shared_grad = Tensor(TensorDim({(unsigned int)max_grad_size}));
+      shared_grad = Tensor(TensorDim({(unsigned int)max_grad_size}), nullptr, false);
```
Comment (zhoonit) [inline nntrainer/tensor/manager.cpp]:
```suggestion
      shared_grad = Tensor({(unsigned int)max_grad_size}, nullptr, false);
```

File: nntrainer/tensor/var_grad.cpp [hunk 18]
```diff
@@ -16,19 +16,18 @@
 
 namespace nntrainer {
 
-Var_Grad::Var_Grad(const TensorDim &dim, bool train, const std::string &name) :
+Var_Grad::Var_Grad(const TensorDim &dim, bool train, bool alloc_now_, const std::string &name) :
```
Comment (zhoonit) [inline nntrainer/tensor/var_grad.cpp]: What's the difference from just having tensor dim and not allocated tensor?

File: nntrainer/tensor/tensor.cpp (hunk 2 above)
Comment (kparichay) [reply nntrainer/tensor/tensor.cpp]: `allocate` is the only function which allocates/sets `data` in tensor.
I didn't want to split it.

File: nntrainer/graph/network_graph.cpp (hunk 11 above)
Comment (kparichay) [reply nntrainer/graph/network_graph.cpp]: Added comments.

File: nntrainer/graph/network_graph.cpp (hunk 15 above)
Comment (kparichay) [reply nntrainer/graph/network_graph.cpp]: Removed in a later commit.

File: nntrainer/tensor/manager.cpp (hunk 16 above)
Comment (kparichay) [reply nntrainer/tensor/manager.cpp:180]: Tensor uses unsigned int, and it causes `unsigned int` vs `long unsigned int` comparison warnings at a lot of places.

File: nntrainer/tensor/var_grad.cpp (hunk 18 above)
Comment (kparichay) [reply nntrainer/tensor/var_grad.cpp]: With alloc_now_ == true, when Var_Grad::initialize() is called, then the tensors memory is allocated.
With alloc_now_ == true, Var_Grad::initialize() will not allocated memory.

`NetworkGraph::inPlaceOptimization` takes place after Tensor in Var_Grad objects have been allocated and initialization has been done. But if the memory is already allocated with initialization, these later optimizations do not reduce the peak memory requirements.

Plus, by separating initialize() and allocate(), all the optimizations to decide how tensors across the layers interface (input and output connectivity between layers) is not required to done every time.

File: nntrainer/tensor/tensor.h (hunk 10 above)
Comment (zhoonit) [reply nntrainer/tensor/tensor.h:888]: Yup

File: nntrainer/tensor/tensor.cpp (hunk 2 above)
Comment (zhoonit) [reply nntrainer/tensor/tensor.cpp]: Sure

File: nntrainer/tensor/manager.cpp (hunk 16 above)
Comment (zhoonit) [reply nntrainer/tensor/manager.cpp:180]: As far as I remember, size_t can effectively check max overflow but unsigned int is not guaranteed as max supported size is different. I guess not a big deal for now

File: nntrainer/layers/conv2d_layer.cpp (hunk 6 above)
Comment (kparichay) [reply nntrainer/layers/conv2d_layer.cpp]: Sounds good, but this would have to be an added interface and not a replacement for the current method.
With just that interface, a layer, not part of the model would not be able to register weights with manager.

File: nntrainer/graph/network_graph.cpp (hunk 14 above)
Comment (kparichay) [reply nntrainer/graph/network_graph.cpp]: designated memory(for safety) -> you mean a designated variable?

File: nntrainer/tensor/manager.cpp (hunk 17 above)
Comment (kparichay) [reply nntrainer/tensor/manager.cpp]: done.

**Comment by kparichay** [comment]
Please note that there will be a wiki page soon on NNTrainer explaining all the memory optimizations.

File: nntrainer/layers/conv2d_layer.cpp (hunk 6 above)
Comment (zhoonit) [reply nntrainer/layers/conv2d_layer.cpp]: If we make sure neuralnetwork calls sth like `manager.trackWeights(layer.getWeights)`. For API point of view, layer does not need to know about the manager.

File: nntrainer/tensor/tensor.h (hunk 12 above)
[the remark this answers is not in the document]
Comment (zhoonit) [reply nntrainer/tensor/tensor.h:71]: Current (before this patch) semantics, `Tensor(TensorDim)` does the work.
So `Tensor(TensorDim, bool allocate_now)` covers all the new semantics

else, I think we could consider tag dispatching.

File: nntrainer/graph/network_graph.cpp (hunk 14 above)
Comment (zhoonit) [reply nntrainer/graph/network_graph.cpp]: yup. sth like `Tensor inPlaceSharedSlot`

or `Tensor & in_place_shared_slot = l->net_hidden[0]->getVariableRef()` for readability

File: nntrainer/layers/conv2d_layer.cpp (hunk 6 above)
Comment (kparichay) [reply nntrainer/layers/conv2d_layer.cpp]: As the API exposes layer functionality, a user cannot then create just a layer (without wrapping it in model), without exposing the manager to the API (which IMO should not be exposed).

File: nntrainer/tensor/manager.cpp (hunk 16 above)
Comment (kparichay) [reply nntrainer/tensor/manager.cpp:180]: Yes, size_t is better, but it requires repo wide updates, which is beyond the scope of this PR.

File: nntrainer/tensor/var_grad.cpp (hunk 18 above)
Comment (zhoonit) [reply nntrainer/tensor/var_grad.cpp]: Yes. I mean `Tensor::Tensor(Tensor&dim, nullptr, false)` vs `TensorDim` instead for non-allocated tensor. Because `allocation` happens always later, In this case `initialize` does not need to deal with `tensor(dim, null, false)` but just `tensordim` or `weights` that wraps around the `tensordim`.

File: nntrainer/tensor/tensor.h (hunk 12 above)
[the remark this answers is not in the document]
Comment (kparichay) [reply nntrainer/tensor/tensor.h:71]: With just `Tensor(TensorDim, bool allocate_now)`, how do you lazy allocate a tensor but with a provided `buf`?

File: nntrainer/tensor/var_grad.cpp (hunk 18 above)
Comment (kparichay) [reply nntrainer/tensor/var_grad.cpp]: `Tensor::Tensor(Tensor&dim, nullptr, false)` vs `Tensor::Tensor(TensorDim)` are different as `alloc_now_` defaults to true.

File: nntrainer/tensor/tensor.h (hunk 12 above)
[the remark this answers is not in the document]
Comment (zhoonit) [reply nntrainer/tensor/tensor.h:71]: if buf is provided, allocate_now should be always true. So there seems no such case.

```
@throws if buf is not null and allow_now is false
```

File: nntrainer/graph/network_graph.cpp (hunk 14 above)
Comment (kparichay) [reply nntrainer/graph/network_graph.cpp]: updated.

File: nntrainer/tensor/var_grad.cpp (hunk 18 above)
Comment (zhoonit) [reply nntrainer/tensor/var_grad.cpp]: Yes, I mean between `Tensor::Tensor(Tensor&dim, nullptr, false)` vs `TensorDim`. And they could share weights (a wrapper of TensorDim in this stage) if needed.
Let's discuss this later as this would be slightly out of boundary of the PR

File: nntrainer/tensor/tensor.h (hunk 12 above)
[the remark this answers is not in the document]
Comment (kparichay) [reply nntrainer/tensor/tensor.h:71]: For this PR. Later, buf will be cached in SrcSharedTensor.
I can do it in this PR itself.

File: nntrainer/tensor/var_grad.cpp (hunk 18 above)
Comment (kparichay) [reply nntrainer/tensor/var_grad.cpp]: I get what you mean. Semantically, they contain the same information. `Tensor::Tensor(Tensor&dim, nullptr, false)` is just a wrapper over `TensorDim` which will later contain memory.

File: nntrainer/tensor/tensor.cpp (hunk 7 above)
Comment (jijoongmoon) [reply nntrainer/tensor/tensor.cpp:397]: Could you add some comments when they are used? and if there is the case which src.data and src.src_tensor is true?

File: nntrainer/tensor/var_grad.cpp [hunk 19]
```diff
@@ -16,19 +16,22 @@
...
+  else
+    grad = std::make_shared<Tensor>();
 }
 
 void Var_Grad::initializeWeight(const Tensor &preallocated) {
   if (!preallocated.uninitialized()) {
-    var = std::make_shared<Tensor>(preallocated);
-  } else {
-    var = std::make_shared<Tensor>(dim);
+    var->makeSharedDataTensor(preallocated);
```
Comment (jijoongmoon) [inline nntrainer/tensor/var_grad.cpp:34]: s/initializeWeight/initializeVariables?

File: nntrainer/tensor/tensor.h (hunk 12 above)
[the remark this answers is not in the document]
Comment (kparichay) [reply nntrainer/tensor/tensor.h]: Updated.

[the remark this answers is not in the document]
Comment (zhoonit) [reply nntrainer/tensor/tensor.h]: Awesome

File: test/test_models/models/mnist_inf.ini [hunk 20]
```diff
@@ -0,0 +1,11 @@
...
+[Model]
+Type = NeuralNetwork	# Network Type : Regression, KNN, NeuralNetwork
+Optimizer = adam 	# adam (Adamtive Moment Estimation)
+Loss = cross  		# Loss function : mse (mean squared error)
+Save_Path = "../test_models/models/model.bin"  	# model path to save / read
+batch_size = 1		# batch size
+
+[mnist]
+backbone = "../test_models/models/mnist.ini"
+Input_Shape = 1:28:28
```
Comment (jijoongmoon) [inline test/test_models/models/mnist_inf.ini:11]: It's how we use backbone!

File: test/unittest/unittest_nntrainer_layers.cpp [hunk 21]
```diff
@@ -1911,6 +1915,7 @@ TEST(nntrainer_LossLayer, forward_loss_unknown_n) {
     layer.getType(), layer.getName(), layer.getOutputDimension()));
 
   manager.initializeTensors(true);
+  manager.allocateTensors();
```
Comment (jijoongmoon) [inline test/unittest/unittest_nntrainer_layers.cpp:1918]: We need this from now on.

File: test/test_models/models/mnist_inf.ini (hunk 20 above)
Comment (kparichay) [reply test/test_models/models/mnist_inf.ini:11]: yes :)

File: test/unittest/unittest_nntrainer_layers.cpp (hunk 21 above)
Comment (kparichay) [reply test/unittest/unittest_nntrainer_layers.cpp:1918]: yes, when using without model.
model.inference() and model.train() call this internally.

File: nntrainer/tensor/var_grad.cpp (hunk 18 above)
Comment (zhoonit) [reply nntrainer/tensor/var_grad.cpp]: Yes and I think var_grad can do this. 
This could be discussed later when we need to reduce the complexity of tensor I guess.

**Review by zhoonit — APPROVED** [review]
LGTM :)

File: nntrainer/tensor/var_grad.cpp (hunk 19 above)
Comment (kparichay) [reply nntrainer/tensor/var_grad.cpp:34]: done as a new commit in this PR.

File: nntrainer/tensor/tensor.cpp (hunk 7 above)
Comment (kparichay) [reply nntrainer/tensor/tensor.cpp:481]: done

File: nntrainer/tensor/var_grad.cpp (hunk 18 above)
Comment (kparichay) [reply nntrainer/tensor/var_grad.cpp]: Yes, to reduce the overhead of tensor object.

**Review by jijoongmoon — APPROVED** [review]
LGTM
