### PR TITLE
[layer] bug fix for array initializer

### LINKED ISSUE #1773: weight indices default value buggy in each layer
weight indices default values in each layer is defaulted to 0 but if not requested, instead of giving out of bounds access will return a different weight. The default value must be set to out of bounds.

### PR DESCRIPTION
**Pull request by kparichay**
Bug fix for array initializer storing the indices of the requested
weight so that accessing weights not requested always causes error.

resolves #1773

Signed-off-by: Parichay Kapoor <pk.kapoor@samsung.com>

### CODE REVIEW

**Review by zhoonit — APPROVED** [review]
great work :)

File: nntrainer/layers/common_properties.h [hunk 1]
```diff
@@ -107,7 +107,7 @@ class Trainable : public nntrainer::Property<bool> {
 };
 
 /**
- * @brief BiasInitializer Initialization Enumeration Information
+ * @brief DisableBias to disable the bias
```
Comment (lhs8928) [inline nntrainer/layers/common_properties.h:110]: 👍

**Review by lhs8928 — COMMENTED** [review]
LGTM

**Review by jijoongmoon — APPROVED** [review]
LGTM
