### PR TITLE
Follow-up after #308

### LINKED ISSUE #315: Add custom exception for some errors
https://github.com/nnstreamer/nntrainer/pull/308#discussion_r454772057

1. Declare custom errors if needed (to `nntrainer_error.h`)
2. Handle it at least at capi exception boundary

### PR DESCRIPTION
**Pull request by zhoonit**
**Changes proposed in this PR:**
- Now friendship between layer and network is over
- Move `setProperty(propType)` to public
- Add custom exception in `_error.h`
- Change `setProperty` `std::out_of_range` ->
`exception::invalid_property`
- Add error code boundary to `nntrainer_exception_boundary`
- Change inherited docs to @copydoc

resolves #315 

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com

### CODE REVIEW

File: api/capi/src/nntrainer.cpp [hunk 1]
```diff
@@ -23,8 +23,8 @@
 #include <databuffer.h>
 #include <databuffer_file.h>
 #include <databuffer_func.h>
-#include <ml-api-common.h>
```
Comment (kparichay) [inline api/capi/src/nntrainer.cpp:26]: huh.. why remove this? ml_train_dataset_create_with_generator() needs this.

Comment (zhoonit) [reply api/capi/src/nntrainer.cpp:26]: I think '*api' can and should solely depend on the <nntrainer_error.h> since #307.
<nntrainer_error.h> is superset of <ml-api-common.h> we have to make a boundary for that.

(theoretically) declaring error code twice otherwise.

Comment (kparichay) [reply api/capi/src/nntrainer.cpp:26]: aah, I confused with nntrainer-api-common.h
