### PR TITLE
[Competibility] Change test reference tolerance @open sesame 04/22 18:25

### LINKED ISSUE #1125: [CI] Test fail on i586
referring to https://github.com/nnstreamer/nntrainer/pull/1123, that test is failing.
I found that i586 wasn't tested beforehand. 

verified with commit as old as f41e0bc74761414c3e44fb0d4975bc6191d22b7e . I think it's okay to not test i586 as the number difference is small and it wouldn't affect the behavior of the library.

Leaving this for the record, I am going to disable i586.

```
[   97s] The output from the failed tests:
[   97s] 
[   97s] 17/26 unittest_ccapi                 FAIL           7.05s (exit status 1)
[   97s] 
[   97s] --- command ---
[   97s] 11:33:33 /home/abuild/rpmbuild/BUILD/nntrainer-0.1.1/build/test/ccapi/unittest_ccapi --gtest_output=xml:/home/abuild/rpmbuild/BUILD/nntrainer-0.1.1/build/unittest_nntrainer_profiler.xml
[   97s] --- Listing only the last 100 lines from a long log. ---
[   97s] Unit = 10
[   97s] Type = fully_connected
[   97s] input_layers = inputlayer
[   97s] 
[   97s] #1/1 [ =                    ] 0% ( Training Loss: 2.42675 )
[   97s] #1/1 [ =======              ] 31% ( Training Loss: 5.60378 )
[   97s] #1/1 [ =============        ] 63% ( Training Loss: 5.27162 )
[   97s] #1/1 - Training Loss: 4.43405 >> [ Accuracy: 8.33333% - Validation Loss : 2.96461 ] 
[   97s] ../test/ccapi/unittest_ccapi.cpp:204: Failure
[   97s]       Expected: model->getValidationLoss()
[   97s]       Which is: 2.964613
[   97s] To be equal to: 2.9646113
```

### PR DESCRIPTION
**Pull request by zhoonit**
- [Competibility] Change test reference value 

```
This patch change tolerance for the `model->getValidationLoss` which
affects in i586

resolves #1125

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com>

```

### CODE REVIEW

File: test/ccapi/unittest_ccapi.cpp [hunk 1]
```diff
@@ -201,7 +201,7 @@ TEST(nntrainer_ccapi, train_with_config_01_p) {
   EXPECT_NO_THROW(model->train());
 
   EXPECT_FLOAT_EQ(model->getTrainingLoss(), 4.434051);
-  EXPECT_FLOAT_EQ(model->getValidationLoss(), 2.9646113);
+  EXPECT_NEAR(model->getValidationLoss(), 2.9646113, 1.0e-5);
```
Comment (kparichay) [inline test/ccapi/unittest_ccapi.cpp:204]: how about reducing tolerance only for i586?

Comment (zhoonit) [reply test/ccapi/unittest_ccapi.cpp:205]: Done

**Review by kparichay — APPROVED** [review]
LGTM

**Review by jijoongmoon — APPROVED** [review]
LGTM
